### ISSUE TITLE
author='Arkadiusz Dzięgiel',

### ISSUE THREAD

**Issue by lorenzo95** [glorpen/docker-hostdns#3]
Hello, 

this tool is exactly what I was looking for. I am trying to get it setup and running. I just wanted to let you know that an out of the box ubuntu 18.04 can't handle the 'ę' character. Throws an error during install. 

root@vm:/etc/bind/docker-hostdns-1.1.1# python setup.py install
  File "setup.py", line 45
SyntaxError: Non-ASCII character '\xc4' in file setup.py on line 45, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Thanks,
Gero

**Comment by glorpen** [comment]
Python2 is simply not supported - try `apt install python3-setuptools` and then `python3 setup.py install` (hopefully in virtualenv :) ).

**Comment by lorenzo95** [comment]
Ah yes, works like a charm. Thank you for your help.
